### PR TITLE
Design admin page with latest repo codebase

### PR DESCRIPTION
**Pull request by nagvanshi9275**
Hey team! I’ve made some updates that I wanted to share.

1. Bug Fix:

In the StudentProfile.js file, I noticed that the gender field was being repeated multiple times. I’ve cleaned that up to make the code easier to read and maintain.

2. Admin Profile Section Redesign:

I gave the admin profile section a complete makeover using Material-UI. The new design looks great and is fully responsive, so it works well on mobile, tablet, and desktop devices. I’ve attached some screenshots so you can see how it looks across different screen sizes

Check out the attached images for a glimpse of the updated design!
Screenshot (350)
Screenshot (352)
Screenshot (353)

I believe these changes will improve the user experience for our admin section while also tidying up the code a bit. Let me know your thoughts!

### CODE REVIEW

**Review by skanarul8002 — APPROVED** [review]

**Comment by skanarul8002** [comment]
@nagvanshi9275 please raise pr for admin profile page only

**Comment by skanarul8002** [comment]
you can check latest code,,please

**Comment by skanarul8002** [comment]
please check latest code where mca-hub project's error modified by our team

**Comment by nagvanshi9275** [comment]
@skanarul8002 look the issue that i have told you like studentprofile.js file has alraedy resolve by your team and . you want i need to create this pr with that latest codebase this is something you mean please let me know so that i get clearity of what i need to do next

**Comment by skanarul8002** [comment]
your can modify admin profile style in your own approach based on latest code base then raise your pr, my team will merge your pr. i think you are understand @nagvanshi9275

**Pull request closed without merging**
