### PR TITLE
FIXES #2 adding forget password functionality

### LINKED ISSUE #2: Forgot Password Functionality
need to work on forgot password functionality
image

### PR DESCRIPTION
**Pull request by Rehannn03**
This Pull request solves issue #2 that was assigned to me. @skanarul8002 
To make this work on your local mention you will need this **.env** variables

> PORT=8081
> MONGO_URL= mongodb+srv://skanarul8093:skanarul8002@projectcluster.4ksacog.mongodb.net/mcaHub?retryWrites=true&w=majority&appName=projectCluster
> JWT_SECRET
> JWT_EXPIRY
> BACKEND_URL
> EMAIL=YOUR EMAIL ID
> PASSWORD=YOUR PASSWORD

To setup your email and password in Nodemailer refer to below video please:
[SETUP VIDEO](https://www.youtube.com/watch?v=cqdAS49RthQ)

If you face any issue while setting up please feel free to reach out!!!

THANK YOU!

### CODE REVIEW

**Comment by skanarul8002** [comment]
@Rehannn03 , please give us demo with fack gmail and jwt secret / jwt expiry and any screenshots related to this then tell here

**Comment by skanarul8002** [comment]
or contact me with this email: skanarul8002@gmail.com

**Comment by Rehannn03** [comment]
https://github.com/user-attachments/assets/177f39f3-ca5a-4acf-8112-4901e91077f2

The above is video demo for it.
But you won't be able to login because when **REGISTERING FOR THE ADMIN** the password is not getting hashed before saving to DB.
Please add that functionality.

Please feel free to reach out.
THANK YOU!

**Comment by skanarul8002** [comment]
@Rehannn03 , please implement all related functionality from your side and achieved forgot password functionality

**Comment by skanarul8002** [comment]
@Rehannn03, please enable the forgot password button link on the frontend and connect it to the backend. I have already added all the required attributes in the environment for deployment, so you can work on it.

**Comment by Rehannn03** [comment]
I would love to work on that.
So I would raise a issue regarding this please assign it to me!!
Thank You.

**Pull request merged**
