### PR TITLE
Dynamic Student Profile Update

### PR DESCRIPTION
**Pull request by shubhamkumaar**
I created a section to update the student profile and display the profile.

### CODE REVIEW

**Comment by shubhamkumaar** [comment]
#4  Updated the profile dynamically 

Step 1 update the profile then logout.
Step 2 Login again and check the profile.

**Comment by skanarul8002** [comment]
please @shubhamkumaar put screenshots here

**Comment by shubhamkumaar** [comment]
image

**Comment by skanarul8002** [comment]
@shubhamkumaar , is this dynamic profile reflect to database also or not. please give some information about data of profiles then i will merge your pr instant

**Comment by shubhamkumaar** [comment]
image
Yes, it reflects in the database also as you can see in the screenshot of the backend console it reflects the data.

**Comment by skanarul8002** [comment]
@shubhamkumaar, you've caused several issues in the project. Before making changes, please think about what the best approach should be. You've implemented something that resembles a Google Form for a particular profile, then updated the data in the database in a similar manner. There are multiple role-based access controls in place, but you haven't followed any of them. For example, if the issue is designing a dynamic student page, it means you should update the data from other roles, like the admin, who adds student details through a form. Then, you can fetch the data from the database and display it dynamically, with extra properties added through the admin's functionality form. But you've created something akin to a Google Form, which is not a good approach.

**Comment by shubhamkumaar** [comment]
Sorry for the understanding but i thought that the student is created by the admin but the small details like DOB, ADDRESS, etc. Can be changed by the so there is less work for the admin and student can update there info by themselves only.

**Comment by skanarul8002** [comment]
@shubhamkumaar  , There is only one role assigned to students, which is shown on their profile as provided by the Admin, like the Head of the Department (HOD). The approach is that when the admin adds a new student, you can modify the form, and the data will be stored in the database. The data can then be fetched normally, and this is the task. I think 🤔 you are understand. Work on it and raise your pr. I will definitely merge. 
Instructions:
1. Fetch updated repo from my repo 
2. Clone in to your different new directory 
3. Modify only admin form that you are understand 
4. Add some extra schemas related to students.
5. extra property used in profile that are already fetched in profile like name, clg name etc....
6. Then verify yourself 
7. Raise your pr
Thanks 👍

**Comment by shubhamkumaar** [comment]
As per my understanding now, I have to change the student profile form to load on the admin, and only the admin can submit that form.
The student profile is only to display. The admin is to add all the details.

**Comment by skanarul8002** [comment]
yeah @shubhamkumaar , you can do it in the admin section and access it from the student's profile. There's no need for extra information like parent details. You can add additional information related to the student to keep the application simple.

**Comment by skanarul8002** [comment]
if @shubhamkumaar  are intersted to work on real life project then send me mail with your details like qualifiaction bg,1st yr or 2nd etc like that.
mail: skanarul8002@gmail.com

**Pull request merged**
